trigger:
- dev

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
    checkLatest: true
  displayName: Install Latest Node Version

- task: CmdLine@2
  inputs:
    script: |
      npm i
  displayName: Install all Dependencies

- task: CmdLine@2
  inputs:
    script: |
      npm install -g jest
  displayName: Install Global Jest

- task: CmdLine@2
  inputs:
    script: 'jest tests/%TEST_NAME% --ci --reporters=jest-junit --reporters=default'
  displayName: Execute Jest Tests
  continueOnError: true


- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'junit.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Unit Tests'
  displayName: Automation Test Results

